global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "platform-auth-service"
    metrics_path: "/actuator/prometheus"
    scheme: "http"
    static_configs:
      - targets: ["platform-auth-service:8081"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

rule_files:
  - /etc/prometheus/alerts/*.yml